# Site settings
title: Rob | Resume
description: Rob K Resume (Check LinkedIn for latest info) 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rob K
user_description: Hi, I'm Rob from Perth, Australia. I'm always searching for another challenge or just something new to learn. Currently anything Accounting, Finance, Financial Derivatives, & Home Lab/AI is my passion. Always learn to self host and automate everything; from Media, CCTV, and even Grocery lists... the list goes on. AI
user_title: BCom Finance & Accounting (UWA)
email: CtrlAltRob@pm.me
#twitter_username: robkoteski
# instagram_username: 
# facebook_username: mauricio.urraco
linkedin_username: robert-koteski
github_username:  exolocity
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
