# Site settings
title: exolocity
description: exolocity
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: exolocity
user_description: Hi, I'm Robert a consultant from Australia, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: B. Comm (Finance & Accounting)
email: rob@exolo.city
twitter_username: robkoteski
# instagram_username: 
# facebook_username: mauricio.urraco
# linkedin_username: murraco
github_username:  exolocity
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
